// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"[轮回插件组]全局变量","status":true,"description":"","parameters":{}},
{"name":"[轮回插件组]云存档系统","status":true,"description":"云存档系统","parameters":{}},
{"name":"index","status":true,"description":"","parameters":{}}
];
